### ISSUE TITLE
Error from logs - Unhandled NODE exception

### ISSUE THREAD

**Issue by deepaksftc** [UserOfficeProject/user-office-project-issue-tracker#1248]
Need to do more analysis on this error and root cause,
[2024-11-15T10:50:54.003Z] ERROR - Unhandled NODE exception 
 {"exception":{"name":"Error","message":"Request aborted","stack":"Error: Request aborted\n    at onaborted (/home/node/app/node_modules/express/lib/response.js:1062:15)\n    at onfinish (/home/node/app/node_modules/express/lib/response.js:1098:50)\n    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)\n    at listener (/home/node/app/node_modules/on-finished/index.js:170:15)\n    at onFinish (/home/node/app/node_modules/on-finished/index.js:101:5)\n    at callback (/home/node/app/node_modules/ee-first/index.js:55:10)\n    at Socket.onevent (/home/node/app/node_modules/ee-first/index.js:93:5)\n    at Socket.emit (node:events:529:35)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)"}}

https://logs.devs.facilities.rl.ac.uk/app/discover#/doc/7e1733e0-d283-11ea-856e-3dc8c807c0b0/kubernetes-bisappslogs-7.13.2-2024.11.15?id=jO9yL5MBPzDmZGpHoKo1

**Comment by mutambaraf** [comment]
@mehta-pooja123  we need priority on this.

**Comment by Scott-James-Hurley** [comment]
[Last 6 months of instances of this error](https://grafana.developers.facilities.rl.ac.uk/goto/afjvonm300zk0d?orgId=1)
